---

- hosts: nova_servers
  become: true
  tasks:

  - name: Install Nova Package (Ubuntu)
    tags: nova
    apt:
      name:
        - nova-compute
        - python3-openstackclient
      state: latest
    when: ansible_distribution == "Ubuntu"
